---
title: "HW13_Javier_Rojas"
author: "Javier Rojas"
date: "12/10/2018"
output: html_document
---

 
##Make Train and Test Datasets 
```{r} 
library(dplyr) 
library(caret)
##TRAIN
if (!exists("mtrain")) {
  mtrain <- read.csv("mnist_train.csv", header=F) %>% as.matrix
  train_classification <- mtrain[,1]  # y values
  y <- factor(train_classification, levels=c(0,1))
  mtrain <- mtrain[,-1]/256  # x matrix
  colnames(mtrain) <- 1:(28^2)
  x <- mtrain[1:1000,]
  colnames(mtrain) <- NULL
  rownames(mtrain) <- NULL
}

y <- rep(NA, length(train_classification))

for (i in 1:length(train_classification)){
  cn <- train_classification[i]
  
  if (cn == 3){
    cn <- 1
  }
  else {
    cn <- 0
  }
  y[i] <- cn
  
}

y <- factor(y, levels = c(0,1))
y <- y[1:1000] 


##TEST  
if (!exists("mtest")){
  mtest <- read.csv("mnist_test.csv", header=F) %>% as.matrix
  train_classification <- mtest[,1]  # y values
  test.y <- factor(train_classification, levels=c(0,1))
  mtest <- mtest[,-1]/256  # x matrix
  colnames(mtest) <- 1:(28^2)
  test.x <- mtest[1:1000,]
  colnames(mtest) <- NULL
  rownames(mtest) <- NULL
}

output.test <- rep(NA, length(train_classification))

for (i in 1:length(train_classification)){
  cn <- train_classification[i]
  
  if (cn == 3){
    cn <- 1
  }
  else {
    cn <- 0
  }
  output.test[i] <- cn
  
}

test.y <- factor(output.test, levels = c(0,1))
test.y <- y[1:1000]
```


##Show Number
```{r} 
library(dplyr)
setwd("/Users/jrojas/Desktop/Intro_Data_Sci")
show_number <- function(m, i, oriented=T)
{
  im <- matrix(mtrain[i,], byrow=T, nrow=28)
  
  if (oriented) {
    im_orient <- matrix(0, nrow=28, ncol=28)
    for (i in 1:28)
      im_orient[i,] <- rev(im[,i])
    
    im <- im_orient
  }
  image(im)
}

show_number(x, 11)
```


##Prediction Error Function
```{r}
prediction_errors <- function(x, y, t_out)
{
  
  y <- factor(y, levels=c(0, 1))
  
  true_y <- y
  pred_y <- predict(t_out, x)
  
  n_samples <- nrow(x)
  error <- sum(true_y != pred_y)/n_samples
  return (error)
}
```


##Set and and Execute Neural Net with Nodes 5-10, Decay = 0 
```{r} 
library(caret)
tuning_df <- data.frame(size=5:10, decay=0)

fitControl <- trainControl(method="none")

fitControl <- trainControl(## 10-fold CV
  method = "repeatedcv",
  number = 2,
  ## repeated ten times
  repeats = 3)



t_out <- train(x=x, y=y, method="nnet",
                      trControl = fitControl,
                      tuneGrid=tuning_df, maxit=1000, MaxNWts = 10000) 
t_out

```

##Set and and Execute Neural Net with Nodes = 5-10, Decay = 1-3 
```{r}
tuning_df <- data.frame(size=5:10, decay=c(1,2,3))

fitControl <- trainControl(method="none")

fitControl <- trainControl(## 10-fold CV
  method = "repeatedcv",
  number = 2,
  ## repeated ten times
  repeats = 3)



t_out <- train(x=x, y=y, method="nnet",
                    trControl = fitControl,
                    tuneGrid=tuning_df, maxit=1000, MaxNWts = 10000) 
t_out
```


##Test Neural Net with Test Data 
```{r}
test_error <- prediction_errors(test.x, test.y, t_out) 

print(c("Test Error: ", test_error))
```

